#ifndef __USERINTERFACE_EXPIMPSPEC_H__
#define __USERINTERFACE_EXPIMPSPEC_H__

#ifdef USERINTERFACE_EXPORTS
#define USERINTERFACE_EXPORT_IMPORT_SPECIFICATOR __declspec(dllexport)
#else
#define USERINTERFACE_EXPORT_IMPORT_SPECIFICATOR __declspec(dllimport)
#endif // USERINTERFACE_EXPORTS

#endif // __USERINTERFACE_EXPIMPSPEC_H__